services:
    postgres:
        image: docker.io/postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: docker.io/redis
        command: ["redis-server", "--protected-mode", "no"]
    api:
        build:
            context: ./server
        image: docker.io/prajitha111/complex_api    
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    worker:
        build: ./worker
        image: docker.io/prajitha111/complex_worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379        
    client:
        build: ./client
        image: docker.io/prajitha111/complex_client
    nginx:
        depends_on:
            - api
            - client
        build: ./nginx
        ports:
            - '8082:80'